### ISSUE TITLE
[Global setting] Remove the focus visible on click

### ISSUE THREAD

**Issue by melissaperreault** [Shopify/dawn#1028]
### Expectation

- [ ] The focus appears on click on product cards https://screenshot.click/21-12-42tah-cs0lp.mp4 and other places. It seems to have been reintroduced. We want to re-adjust it back to not display on click.

**Comment by KaichenWang** [comment]
### Potential solution

#### Before
```css
.card-wrapper:focus-within .card {
  box-shadow: 0 0 0 .3rem rgb(var(--color-background)),0 0 .5rem .4rem rgba(var(--color-foreground),.3);
  outline-offset: 0.3rem;
  outline: .2rem solid rgba(var(--color-foreground),.5);
}

.card-wrapper:focus-within .card__heading a {
  box-shadow: none;
  outline: 0;
}
```

####  After
```css
.card__heading a:focus:after {
  box-shadow: 0 0 0 .3rem rgb(var(--color-background)),0 0 .5rem .4rem rgba(var(--color-foreground),.3);
  outline-offset: 0.3rem;
  outline: .2rem solid rgba(var(--color-foreground),.5);
}

.card__heading a:focus-visible:after {
  box-shadow: 0 0 0 .3rem rgb(var(--color-background)),0 0 .5rem .4rem rgba(var(--color-foreground),.3);
  outline-offset: 0.3rem;
  outline: .2rem solid rgba(var(--color-foreground),.5);
}

.card__heading a:focus:not(:focus-visible):after {
  box-shadow: none;
  outline: 0;
}

.card__heading a:focus {
  box-shadow: none;
  outline: 0;
}
```
