### ISSUE TITLE
Grid - Vertical spacing after last row

### ISSUE THREAD

**Issue by KaichenWang** [Shopify/dawn#1054]
**Describe the current behavior**

Grid `vertical space` global setting allows for up to 72px padding between grid rows. This bottom padding is applied to items in the last row of the grid.

**Describe the expected behavior**

The Grid `vertical space` setting value should be applied as padding between grid rows, but not on the last row.

**Version information (Dawn, browsers and operating systems)**
- Dawn branch: `all-global-settings`
- Chrome Version 95.0.4638.69
- macOS Version  12.0.1

**Possible solution**

Add negative bottom margin to the grid container. Since this affects multiple sections, this requires thorough testing.

``` css
.grid {
  margin-bottom: calc(0px - var(--grid-mobile-vertical-spacing));
}

@media screen and (min-width: 750px) {
  .grid {
    margin-bottom: calc(0px - var(--grid-desktop-vertical-spacing));
  }
}
```

**Additional context/screenshots**

The key is ensure consistent behavior that makes sense in multiple scenarios

#### Featured collection
![Screen_Shot_2021-12-21_at_10_03_28_AM](https://user-images.githubusercontent.com/3710548/146952265-0212f0f7-8694-47f3-bb03-fac34ed7466f.jpg)

#### Collection with pagination
![Screen_Shot_2021-12-21_at_10_03_15_AM](https://user-images.githubusercontent.com/3710548/146952251-dd26768e-e6a2-4fbe-ac48-5cf7f61d0571.jpg)

#### Collection without pagination
![Screen_Shot_2021-12-21_at_10_03_41_AM](https://user-images.githubusercontent.com/3710548/146952277-b399ad34-0496-4ed7-b8ce-cfae1ef1dc75.jpg)
