### ISSUE TITLE
Multicolumn spacing impacted by swipe on mobile setting when it shouldn't

### ISSUE THREAD

**Issue by ludoboludo** [Shopify/dawn#1387]
**Describe the current behavior**

I noticed some of styling in multicolumn, for the slider is impacting the desktop spacing due to: 
```css
.background-none .slider .multicolumn-card__info {
  padding-bottom: 0;
}
.background-none .slider .multicolumn-card__info {
  padding-left: 0.5rem;
}
```

And I'm not sure when this is needed: 
```css
.background-none
  .slider
  .multicolumn-card__image-wrapper
  + .multicolumn-card__info {
  padding-left: 1.5rem;
}
```

[Video recap](https://screenshot.click/22-24-udb5l-lyi54.mp4).

**Version information (Dawn, browsers and operating systems)**
- Dawn Version: 3.0.0
- Chrome Version 91.0.4472.114
- macOS Version 11.3.1
