### ISSUE TITLE
[CI] Lighthouse updates

### ISSUE THREAD

**Issue by andrewetchen** [Shopify/dawn#1632]
Reminders for me to look into the following:

**Lighthouse CI**

We are currently a [deprecated authentication config](https://github.com/Shopify/lighthouse-ci-action#deprecated-authentication-configuration) for our Lighthouse CI job: `app_id` and `app_password` are deprecated.

https://github.com/Shopify/dawn/blob/3591cdf89b3d9e93541096e41bf3d5f8b8be674a/.github/workflows/ci.yml#L4-L16

https://github.com/Shopify/lighthouse-ci-action/blob/13cf9a620e4d97fb36b2e5a87dae2eefc2670f21/action.yml#L43-L50

```yml
...
  app_id:
    description: '(deprecated) Shopify private app ID'
    depreciationMessage: Shopify private apps are deprecated. Use a Custom App `access_token` instead.
    required: false
  app_password:
    description: '(deprecated) Shopify private app password'
    depreciationMessage: Shopify private apps are deprecated. Use a Custom App `access_token` instead.
    required: false
...
```

We should use the [Custom app authentication](https://github.com/Shopify/lighthouse-ci-action#authentication) method.

---

Add leaving `v` by changing `shopify/lighthouse-ci-action@1.0` to `shopify/lighthouse-ci-action@v1`: this might not be too critical as Github doesn't currently apply any versioning semantics for actions but they might in the future and its good practice.

https://github.com/Shopify/dawn/blob/3591cdf89b3d9e93541096e41bf3d5f8b8be674a/.github/workflows/ci.yml#L10

This was also recently changed on the [lighthouse-ci-action repo](https://github.com/Shopify/lighthouse-ci-action/commit/13cf9a620e4d97fb36b2e5a87dae2eefc2670f21).

I tested this by pushing a test commit and let the CI do its thing:
- https://github.com/Shopify/dawn/runs/6070248681?check_suite_focus=true

  <img src="https://user-images.githubusercontent.com/28404165/163896104-382c70da-abd5-4ede-9def-e3bf96815c9a.png" width="500" height="auto">
