### ISSUE TITLE
Button in the facets filter don't fit small screens

### ISSUE THREAD

**Issue by wineworlds** [Shopify/dawn#1977]
On small Screens, the button in the facets filter is too small for large fonts and/or long words, depending on your language.
https://snipboard.io/qTQnHh.jpg

This is caused by css in assets/component-facets.css

```css
/* on line 869 */
.mobile-facets__footer {
  border-top: 0.1rem solid rgba(var(--color-foreground), 0.08);
  padding: 2rem;
  bottom: 0;
  position: sticky;
  display: flex;
  z-index: 2;
  margin-top: auto;
  background-color:rgb(var(--color-background));
  background: var(--gradient-background);
}

/* on line 885 */
.mobile-facets__footer > * {
  width: 50%;
}
```

**Possible solution**

Delete `.mobile-facets__footer > *` on line 885 and extend `.mobile-facets__footer` with `flex-direction` and `gap` with mediaquery

```css
.mobile-facets__footer {
  border-top: 0.1rem solid rgba(var(--color-foreground), 0.08);
  padding: 2rem;
  bottom: 0;
  position: sticky;
  display: flex;
  flex-direction: column;
  gap: 2rem;
  z-index: 2;
  margin-top: auto;
  background-color:rgb(var(--color-background));
  background: var(--gradient-background);
}

@media only screen and (min-width: 445px) {
  .mobile-facets__footer {
    flex-direction: row;
    gap: 2rem;
  }
}
```

https://snipboard.io/ponRSL.jpg

**Version information (Dawn, browsers and operating systems)**
- Dawn Version: 7.0.0
- Chrome Version 91.0.4472.114
- macOS Version 11.3.1
