### ISSUE TITLE
[Rich text] Follow up to improve unordered and ordered lists

### ISSUE THREAD

**Issue by andrewetchen** [Shopify/dawn#2219]
### Improve rich text unordered and ordered lists

This issue was created as a follow up to further improve upon:

- https://github.com/Shopify/dawn/pull/2185

https://github.com/Shopify/dawn/pull/2185#issuecomment-1376393156

> One question I had was if we can control the margin between the bullet and the first letter. It looks a little far away in general. We can pair to discuss what I mean.

I see what you mean and I agree that it could be a little closer. Unfortunately, there's currently not many [allowable properties](https://developer.mozilla.org/en-US/docs/Web/CSS/::marker#allowable_properties) that we can use for the `::marker` pseudo-element, including margin and padding.

> There is the subsequent line that we would need to polish too, so it can [follow the indentation as well](https://screenshot.click/23-31-24hq5-zvozv.png).

I agree and something else I noticed while working on a potential indentation fix was that it renders differently on Chrome, Firefox, and Safari using the following CSS (subtle but still noticeable):

<details><summary>CSS (initial indentation fix)</summary>

- I added this to assets/`component-rte.css`

  ```css
  .rte ul,
  .rte ol {
    list-style-position: inside;
    padding-left: 2rem;
  }

  .rte li {
    padding-left: 2.75rem;
    text-indent: -2.05rem;
  }

  @media screen and (min-width: 750px) {
    .rte li {
      text-indent: -2.2rem;
    }
  }
  ```

</details>

<details><summary>Screenshot (Chrome, Firefox, Safari)</summary>

  ![image](https://user-images.githubusercontent.com/28404165/211415747-8bb0ab9e-5137-4c89-8e71-8e9575fd603d.png)

</details>
