### ISSUE TITLE
Desktop: Header: Dropdown menu animation works intermittently

### ISSUE THREAD

**Issue by vfonic** [Shopify/dawn#2220]
## Describe the current behavior

When you open a header dropdown menu for the first time, the menu opens with a nice slide down (transform translateY) + fade in (opacity) animation.
When closing the menu, the menu instantly disappears, with no animation.
When opening the menu again, the menu _sometimes_ opens with animation, and sometimes without.

## Describe the expected behavior

The menu should always open/close with animation.

## Version information (Dawn, browsers and operating systems)

- Dawn Version: 7.0.1
- Chrome Version 108.0.5359.124
- macOS Version 13.1

## Possible solution

I believe the issue lies with `animateMenuOpen` animation paired with `animation-fill-mode: forwards;`.

If I replace that with:

```css
.js details > .header__submenu {
  opacity: 0;
  transform: translateY(-1.5rem);
  transition: all 0.3s ease;
}
.js details[open] > .header__submenu {
  opacity: 1;
  transform: translateY(0);
}
```

It works perfectly.
I understand there's more to it (`prefers-reduced-motion` etc.), so I'm not sure what's the best solution that works for everyone.

Perhaps this would suffice:

```css
@media (prefers-reduced-motion) {
  .js details > .header__submenu {
    transition: none;
  }
}
```

## Additional context/screenshots

Latest Dawn theme from Shopify Theme store (I didn't check on latest `main` branch):

https://user-images.githubusercontent.com/67437/212420395-790203e5-3204-4120-88d1-5d80104d1ec7.mov
