### ISSUE TITLE
[Image with text] Adapt to image isn't respected when text is long

### ISSUE THREAD

**Issue by ludoboludo** [Shopify/dawn#2949]
## Describe the current behavior
When the text is longer than the image, the image is then not respecting it's original sizing. 

## Describe the expected behavior
When set to `Adapt to image` it should keep the original sizing of the image

## Version information (Dawn, browsers and operating systems)

- Dawn Version: 7.0.1 +
- Chrome Version 108.0.5359.124
- macOS Version 13.1

## Possible solution
Looks like a good potential fix would be: 
```css
..image-with-text__media--adapt.image-with-text__media {
  min-height: inherit;
}
```
But we would need to test with all the different settings of that section (layout options, animations)

## Additional context/screenshots

![](https://screenshot.click/09-09-yi4fj-02ig4.png)
