### ISSUE TITLE
Investigate webkit autofill style fix

### ISSUE THREAD

**Issue by kmeleta** [Shopify/dawn#477]
Follow up to #422 

As discovered in #422 and "fixed" in https://github.com/Shopify/dawn/pull/451 webkit browsers (chrome/safari) force style changes to input fields when they have been autofilled. When I investigated, it didn't appear the browsers allow you to override or prevent these internal styles.

I saw 3 ways to deal with it, but maybe someone is aware of something else to try..
1. Embrace the functionality and make adjustments on our end so that everything remains readable (implemented solution)
2. Use `autocomplete="off"` to prevent the autofill functionality altogether (bad ux)
3. Investigate a hack using css `box-shadow` to create a faux background ([codepen example](https://codepen.io/kmeletashop/pen/mdwyJWM))

If design decides they are interested in preventing the default browser behavior instead of the current fix in dawn, we can look into applying the third option. We'd need to investigate it more and see if it's even feasible. It's also probably debatable whether this would be a good idea or not, but it would certainly look nicer. Currently though we are using the `box-shadow` prop to create the borders of our inputs so we'd have to rework that for this to work.

**Comment by kmeleta** [comment]
cc: @melissaperreault

**Comment by gideonb** [comment]
Another cheeky option is to set a _very_ long transition time:
```css
input:-webkit-autofill,
input:-webkit-autofill:hover,
input:-webkit-autofill:focus,
input:-webkit-autofill:active {
  transition: background-color 5000s ease-in-out 0s, border-color 5000s ease-in-out 0s;
  -webkit-text-fill-color: var(--text);
}
```
It will eventually change color, but probably not before you submit the form.
