### ISSUE TITLE
[Global] Animation persists when reduce motion is enabled

### ISSUE THREAD

**Issue by svinkle** [Shopify/dawn#756]
## Issue summary

Through out Dawn theme there are various, subtle animation. Ex., navigation drop-down, product card hover, blog post hover, etc. These animations persist when the user has set their [operating system accessibility settings to reduce motion](https://www.smashingmagazine.com/2020/09/design-reduced-motion-sensitivities/#reduced-motion-from-the-users-perspective).

Current animations could cause issues for folks with a Vestibular disorder or anyone susceptible to motion sickness, specifically the viewport-wide sweeping motion when a blog post item is moused over.

<details>
  <summary>Screenshots</summary>

  ![Gif animation of Dawn blog list page. A mouse cursor hovers over each item showcasing a viewport-wide zoom animation of the blog post image.](https://user-images.githubusercontent.com/1392632/136578802-7c433735-3c42-42e4-a3a2-cf7d97f6aa39.gif)
</details>

#### CSS

```css
.article-content:hover img {
  transform: scale(1.07);
}
.article-content img {
  transition: transform var(--duration-long) ease;
}

/* … */

.card-wrapper:hover .media.media--hover-effect > img + img {
  /* … */
  transition: transform var(--duration-long) ease;
  transform: scale(1.03);
}

/* … */

.media > img {
  /* … */
  transition: opacity 0.4s cubic-bezier(0.25, 0.46, 0.45, 0.94);
}

/* … */

.header__inline-menu details[open] > .header__submenu {
  /* … */
  transform: translateY(0);
  animation: animateMenuOpen var(--duration-default) ease;
  /* … */
}
```

## Steps to reproduce

1. Go to a Dawn theme store with a password enabled with any supported browser
2. Navigate to the Blog listing page
3. Mouse-over blog items with images

### Expected

- Animation to be lowered or cease completely with reduced motion setting enabled.

### Actual

- Animations persist.

## Recommendation

**Up for discussion.**

Adjust the `transition`/`transform` values to lessen the animation (or consider removing completely) when the reduce motion operating system setting is enabled.

Use the `prefers-reduced-motion` CSS media query to achieve the desired affect.

#### CSS

```css
@media screen and (prefers-reduced-motion) {
  .article-content:hover img {
    transform: none;
  }
  .article-content img {
    transition: none;
  }
}
```

<!-- #### Diff

```diff
- line removed
+ line added
``` -->

## Specifications

- **Browser:** Any
- **Dawn version:** 2.2.0
- **Component:** Global
- **WCAG Principal:** Operable
- **WCAG SC:** [2.3.3 Animation from Interactions](https://www.w3.org/WAI/WCAG21/Understanding/animation-from-interactions.html)
- **Severity:** Medium
- **Effort:** Low
