### ISSUE TITLE
Content jumps when opening and closing search on desktop

### ISSUE THREAD

**Issue by baldurh** [Shopify/dawn#784]
**Describe the current behavior**

Content jumps when opening and closing the search on desktop

![dawn-search-before](https://user-images.githubusercontent.com/1823617/137621258-477186d5-9884-4dff-989f-6eb2aecdc1cd.gif)

**Describe the expected behavior**

Content should not jump

![dawn-search-after](https://user-images.githubusercontent.com/1823617/137621264-2602d0e0-1aed-4445-83d9-da40725ebd51.gif)

**Version information (Dawn, browsers and operating systems)**
- Dawn Version: 2.3.0
- Chrome Version 94.0.4606.81
- macOS Version 11.6

**Possible solution**

```css
.overflow-hidden {
    position: fixed;
    height: 100vh;
    width: 100%;
    overflow-x: hidden;
    overflow-y: scroll;
}
```
